#!/bin/bash
# vendor-daemonkit.sh — hard-copy GMCCDaemonKit sources from the gmcc-marketplace
# repo into Vendor/GMCCDaemonKit so GMVibes builds standalone.
#
# Pulls from the marketplace's git remote (shallow clone), never from a local
# checkout, so any developer can run it with nothing but git installed.
#
# Usage: scripts/vendor-daemonkit.sh [branch]
#   branch                 marketplace branch/tag to copy from (default: main)
#   GMCC_MARKETPLACE_REPO  override the repo to clone from — any git URL or a
#                          local path (useful for forks or testing uncommitted
#                          protocol work; a local path still copies only
#                          committed history, never the working tree)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MARKETPLACE_REPO="${GMCC_MARKETPLACE_REPO:-https://github.com/BRubinson/gmcc-marketplace.git}"
SRC_SUBDIR="plugins/gmcc/daemon/Sources/GMCCDaemonKit"
VENDOR_DIR="$REPO_ROOT/Vendor/GMCCDaemonKit"
BRANCH="${1:-main}"

TMP_CLONE="$(mktemp -d "${TMPDIR:-/tmp}/vendor-daemonkit.XXXXXX")"
trap 'rm -rf "$TMP_CLONE"' EXIT

echo "Cloning $MARKETPLACE_REPO @ $BRANCH (shallow)"
if ! git clone --quiet --depth 1 --branch "$BRANCH" "$MARKETPLACE_REPO" "$TMP_CLONE"; then
    echo "error: could not clone ref '$BRANCH' from $MARKETPLACE_REPO" >&2
    exit 1
fi
COMMIT="$(git -C "$TMP_CLONE" rev-parse --short HEAD)"

echo "Vendoring GMCCDaemonKit from $BRANCH @ $COMMIT"

# Stage into the temp dir first so a bad branch never guts the existing copy.
STAGE="$TMP_CLONE/extract"
mkdir -p "$STAGE"
git -C "$TMP_CLONE" archive HEAD -- "$SRC_SUBDIR" \
    | tar -x -C "$STAGE" --strip-components 4

if [ ! -d "$STAGE/GMCCDaemonKit" ] \
   || [ -z "$(find "$STAGE/GMCCDaemonKit" -name '*.swift' -print -quit)" ]; then
    echo "error: no Swift sources landed — does $SRC_SUBDIR exist on $BRANCH?" >&2
    exit 1
fi

rm -rf "$VENDOR_DIR/Sources"
mkdir -p "$VENDOR_DIR/Sources"
mv "$STAGE/GMCCDaemonKit" "$VENDOR_DIR/Sources/GMCCDaemonKit"

# Library-only manifest, owned by this script. The upstream Package.swift also
# declares the gm/gmcc_daemon executables (and ArgumentParser), which GMVibes
# must not inherit.
cat > "$VENDOR_DIR/Package.swift" <<'EOF'
// swift-tools-version:6.0

// GENERATED by scripts/vendor-daemonkit.sh — do not edit by hand.
// Library-only vendored copy of GMCCDaemonKit from gmcc-marketplace
// (plugins/gmcc/daemon). Re-run the script to refresh; see VENDORED.md
// for the source branch and commit.

import PackageDescription

let package = Package(
    name: "GMCCDaemonKit",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "GMCCDaemonKit", targets: ["GMCCDaemonKit"]),
    ],
    dependencies: [
        .package(url: "https://github.com/groue/GRDB.swift.git", from: "7.0.0"),
    ],
    targets: [
        .target(
            name: "GMCCDaemonKit",
            dependencies: [
                .product(name: "GRDB", package: "GRDB.swift")
            ]
        ),
    ]
)
EOF

cat > "$VENDOR_DIR/VENDORED.md" <<EOF
# Vendored GMCCDaemonKit

Hard copy of \`$SRC_SUBDIR\` from the gmcc-marketplace repo.
Do not edit these sources here — change them upstream and re-vendor.

- Source repo: $MARKETPLACE_REPO
- Branch: $BRANCH
- Commit: $COMMIT
- Vendored: $(date -u +%Y-%m-%dT%H:%M:%SZ)

Refresh with: \`scripts/vendor-daemonkit.sh [branch]\`
EOF

COUNT="$(find "$VENDOR_DIR/Sources/GMCCDaemonKit" -name '*.swift' | wc -l | tr -d ' ')"
echo "Done: $COUNT Swift files → Vendor/GMCCDaemonKit (from $BRANCH @ $COMMIT)"
